server:
  port: 8080

spring:
  datasource:
    username: root
    password: chicago2886_KRinge
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        show-sql: true
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru
      name: Светловка
    - url: https://ipfran.ru
      name: ИПФ РАН
    - url: https://www.playback.ru
      name: PlayBack.Ru

connection-configuration:
  user: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
  referrer: http://www.google.com