server:
  port: 8080

spring:
  datasource:
    username: root
    password: search_587-Engine
    url: jdbc:postgresql://localhost:5432/search_engine
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        show-sql: true
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru
      name: Светловка
    - url: https://ipfran.ru
      name: ИПФ РАН
    - url: https://www.playback.ru
      name: PlayBack.Ru

connection-configuration:
  user: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
  referrer: http://www.google.com